# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iGGcXO_UL2ISFl-NbSItwyTlvO-7mZTM
"""

print("BOOKS AVAILABLE:\n1.harry potter\n2.sherlock holmes\n3.beauty and the beast\n")
print("Enter your details for our records:")
name=input("Enter your name:")
age=int(input("Enter your age:"))
harry=300
sherlock=250
beauty=150
rate1=harry + sherlock
rate2=harry + beauty
rate3=sherlock+beauty
rate4=harry+sherlock+beauty
print("1.harry potter\n2.sherlock holmes\n3.beauty and the beast\n4.harry potter and sherlock holmes\n5.harry potter and beauty and the beast\n6.sherlock holmes and beauty and the beast\n7.all the three books\n")
while True:
    choice=input("Enter your choice(1,2,3,4,5,6,7):")
    if choice in ('1','2','3','4','5','6','7'):
        if choice == '1':
            print("The amount you have to pay for the book is:", harry)
        if choice == '2':
            print("The amount you have to pay for the book is:", sherlock)
        if choice == '3':
            print("The amount you have to pay for the book is:", beauty)
        if choice == '4':
            print("The amount you have to pay for the book is:", rate1) 
        if choice == '5':
            print("The amount you have to pay for the book is:", rate2)
        if choice == '6':
            print("The amount you have to pay for the book is:", rate3)
        if choice == '7':
            print("The amount you have to pay for the book is:", rate4)
        break
    else:
        print("OOPS! The book you are looking for is not available,We will try gettig you the book next time!")
print("wohooo!!! you get a discount of 20%")

amountpaid = int(input("enter amount you have to pay:"))
print("amount paid:", amountpaid)
discounted_amount=(20/100)*(amountpaid)
amt = amountpaid - discounted_amount
print("Your dicounted amount:", amt)

print("YOU ALSO GET A MEMBERSHIP OF OUR STORE\n")
print("Your details as per our records:")
print("Your name:",name)
print("Your age:",age)
print("membership validity : september 2021\n")
print("You can access your membership anytime till september 2021\n")
print("THANKYOU!!! visit us again!!!")